### ISSUE TITLE
CoreUI 3 Pro npm run build failed

### ISSUE THREAD

**Issue by DubStepMad** [coreui/coreui-react#102]
Got a pro license, change the theme to dark via `/src/scss/style.scss`

Keep getting this issues.

```{
  "status": 1,
  "file": "C:/Users/DubStepMad/Desktop/coreui-pro-bootstrap-admin-template_3.0.0-rc.1/src/scss/style.scss",
  "line": 10,
  "column": 1,
  "message": "File to import not found or unreadable: node_modules/@coreui/coreui-pro/scss/themes/dark/coreui-dark.",
  "formatted": "Error: File to import not found or unreadable: node_modules/@coreui/coreui-pro/scss/themes/dark/coreui-dark.\n        on line 10 of src/scss/style.scss\n>> @import \"node_modules/@coreui/coreui-pro/scss/themes/dark/coreui-dark\";\n\n   ^\n"
}```

```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\DubStepMad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.11.3
3 info using node@v11.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~prebuild: @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1
6 info lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1
7 verbose lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: PATH: C:\Users\DubStepMad\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\DubStepMad\Desktop\coreui-pro-bootstrap-admin-template_3.0.0-rc.1\node_modules\.bin;;;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;E:\xampp\php;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\ProgramData\ComposerSetup\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Yarn\bin\;C:\Users\DubStepMad\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\DubStepMad\AppData\Local\Programs\Python\Python38-32\;C:\Program Files\Conan\conan;C:\Users\DubStepMad\AppData\Local\Microsoft\WindowsApps;C:\Users\DubStepMad\AppData\Roaming\npm;C:\Users\DubStepMad\AppData\Roaming\Composer\vendor\bin;C:\Users\DubStepMad\AppData\Local\atom\bin;C:\Program Files\heroku\bin;C:\Users\DubStepMad\AppData\Local\Microsoft\WindowsApps;;E:\Programs\Microsoft VS Code\bin;C:\Users\DubStepMad\AppData\Local\Yarn\bin;C:\Program Files\CMake\bin
9 verbose lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: CWD: C:\Users\DubStepMad\Desktop\coreui-pro-bootstrap-admin-template_3.0.0-rc.1
10 silly lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: Args: [ '/d /s /c',
10 silly lifecycle   'npm-run-all build-clean --parallel css js copy --sequential build-vendors' ]
11 silly lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: Returned: code: 1  signal: null
12 info lifecycle @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1~build: Failed to exec build script
13 verbose stack Error: @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1 build: `npm-run-all build-clean --parallel css js copy --sequential build-vendors`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\DubStepMad\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\DubStepMad\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1
15 verbose cwd C:\Users\DubStepMad\Desktop\coreui-pro-bootstrap-admin-template_3.0.0-rc.1
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DubStepMad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.7.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1 build: `npm-run-all build-clean --parallel css js copy --sequential build-vendors`
22 error Exit status 1
23 error Failed at the @coreui/coreui-pro-bootstrap-admin-template@3.0.0-rc.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xidedix** [comment]
Hi @DubStepMad 

For CoreUI Pro v3 there is no need to change src/scss/styles.scss.
You can switch to the dark theme by adding `c-dark-theme` class to the c-app element.

Closed. It's irrelevant to CoreUI v2 for React.
