### ISSUE TITLE
Cannot load the index.html after npm build

### ISSUE THREAD

**Issue by eraccn** [coreui/coreui-react#194]
Hello,
When I use npm build the package the CoreUI, and apply nginx as the server, I saw the errors:
`
react-dom.production.min.js:216 ChunkLoadError: Loading chunk 8 failed.
(error: http://127.0.0.1:3000/datapack/static/js/8.e32dd374.chunk.js)
    at Function.a.e (http://127.0.0.1:3000/:1:3866)
    at http://127.0.0.1:3000/static/js/6.dff20e85.chunk.js:1:3198
    at O (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:201029)
    at Wl (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:315877)
    at Cc (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:302471)
    at Ec (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:302399)
    at xc (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:302262)
    at yc (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:299228)
    at http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:248607
    at e.unstable_runWithPriority (http://127.0.0.1:3000/static/js/5.ceac300b.chunk.js:2:326026)
......
Manifest: Line: 1, column: 1, Syntax error.
`
OS: Win10
Nginx: 1.21.0
CoreUI: v4

**Comment by eraccn** [comment]
CoreUI is v3 not v4. Sorry.
